/* Turn content/blog/*.md into data the app can import, at BUILD time.
 *
 * Build-time rather than runtime for two reasons: no markdown parser ships in
 * the bundle, and the resulting HTML is what the prerenderer needs to emit real
 * crawlable pages. A client-rendered article is invisible to Telegram and
 * WhatsApp link previews, which do not execute JS — and that is how these get
 * shared in Iran.
 *
 *   node scripts/build-blog.mjs
 * Run automatically by the dashboard's prebuild script.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SRC = path.join(ROOT, "content", "blog");
const APPS = ["dashboard", "pwa"];

// marked lives in dashboard's devDependencies; resolve from there for both apps.
const { marked } = require(path.join(ROOT, "dashboard", "node_modules", "marked"));
marked.setOptions({ gfm: true, breaks: false });

/* Minimal front-matter reader. The files are generated by us and the format is
   fixed, so a full YAML parser would be more surface than the job needs — but
   anything unparseable throws rather than silently publishing a broken page. */
function parseFrontMatter(raw, file) {
  if (!raw.startsWith("---")) throw new Error(`${file}: missing front matter`);
  const end = raw.indexOf("\n---", 3);
  if (end < 0) throw new Error(`${file}: unterminated front matter`);
  const head = raw.slice(3, end).trim();
  const body = raw.slice(end + 4).replace(/^\s*\n/, "");
  const meta = {};
  for (const line of head.split("\n")) {
    const i = line.indexOf(":");
    if (i < 0) continue;
    const k = line.slice(0, i).trim();
    const v = line.slice(i + 1).trim();
    try { meta[k] = JSON.parse(v); } catch { meta[k] = v.replace(/^"|"$/g, ""); }
  }
  return { meta, body };
}

// Reading time from words, and for Persian from characters — Persian words are
// longer and a word count understates how long the piece actually takes.
function readingMinutes(text, lang) {
  const words = text.trim().split(/\s+/).length;
  const wpm = lang === "fa" ? 140 : 200;
  return Math.max(1, Math.round(words / wpm));
}

function build() {
  if (!fs.existsSync(SRC)) { console.error("no content/blog directory"); process.exit(1); }
  const files = fs.readdirSync(SRC).filter(f => /\.(fa|en|zh|ru|es|pt)\.md$/.test(f));
  const posts = [];

  for (const file of files) {
    const raw = fs.readFileSync(path.join(SRC, file), "utf8");
    const { meta, body } = parseFrontMatter(raw, file);
    for (const k of ["slug", "lang", "title", "description", "date"]) {
      if (!meta[k]) throw new Error(`${file}: front matter is missing "${k}"`);
    }
    // Drafts are excluded from the build entirely rather than hidden by CSS —
    // an unpublished article should not be reachable, indexable or in the
    // sitemap just because nothing links to it.
    if (meta.status && meta.status !== "published") {
      console.log(`  skip (${meta.status}): ${file}`);
      continue;
    }
    posts.push({
      slug: meta.slug, lang: meta.lang, title: meta.title,
      description: meta.description, date: meta.date,
      keywords: meta.keywords || [], primaryKeyword: meta.primaryKeyword || "",
      dir: meta.dir || (meta.lang === "fa" ? "rtl" : "ltr"),
      readingMinutes: readingMinutes(body, meta.lang),
      html: marked.parse(body),
    });
  }

  // Newest first, and group translations so the UI can offer them.
  posts.sort((a, b) => String(b.date).localeCompare(String(a.date)) || a.slug.localeCompare(b.slug));
  const langsBySlug = {};
  for (const p of posts) (langsBySlug[p.slug] ||= []).push(p.lang);
  for (const p of posts) p.translations = langsBySlug[p.slug];

  const payload = { generatedAt: null, posts };
  for (const app of APPS) {
    const out = path.join(ROOT, app, "src", "blog-data.json");
    if (!fs.existsSync(path.dirname(out))) continue;
    fs.writeFileSync(out, JSON.stringify(payload, null, 1));
    console.log(`  ${app}/src/blog-data.json — ${posts.length} published post(s)`);
  }
  if (!posts.length) {
    console.log("  (no published posts — every article is still status: draft)");
  }
}

build();
